name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  fpdart: ^1.1.0
  google_fonts: ^6.2.1
  flutter_vector_icons: ^2.0.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.6.2
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  animate_do: ^3.3.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  animated_read_more_text: ^0.0.6
  url_launcher: ^6.3.0
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 23

flutter_native_splash:
  color: "#e8e5e5"
  image: assets/splash_icon.png

  android_12:
    image: assets/splash_icon.png

    # Splash screen background color.
    color: "#e8e5e5"

flutter:
  uses-material-design: true

  assets:
    - assets/
